using HomeWork_13.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using HomeWork_13.ViewModels;
namespace HomeWork_13
{
    /// <summary>
    /// Логика взаимодействия для Clients.xaml
    /// </summary>
    public partial class Clients: Page 
    {
        public Clients()
        {
            InitializeComponent();
        } 
        /// <summary>
        /// Правило для автосоздания стлобцов DataGrid 
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        void gridAutoGeneratedColumnsEvent(object sender,DataGridAutoGeneratingColumnEventArgs e)
        {

            string header = e.Column.Header.ToString();

            if(!String.IsNullOrWhiteSpace(header))
            {
                switch (header)
                {
                    case "Id":
                        e.Column.Header = "ID";
                        e.Column.DisplayIndex = 0;
                            break;
                    case "Client_full_name":
                        e.Column.Header = "ФИО";
                        e.Column.DisplayIndex = 1;
                        break;
                    case "Address":
                        e.Column.Header = "Адрес";
                        e.Column.DisplayIndex = 2;
                        break;
                    case "Phone_number":
                        e.Column.Header = "Телефон";
                        e.Column.DisplayIndex = 3;
                        break;
                    case "CompanyDirector":
                        e.Column.Header = "Директор";
                        e.Column.DisplayIndex = 4;
                        break;
                    case "Type":
                        e.Column.Header = "Форма";
                        e.Column.DisplayIndex = 5;
                        break;
                    default:
                        e.Column.Visibility = Visibility.Hidden;
                        break;

                }
            }
            
        }
        private void OpenCartInfo(object sender, RoutedEventArgs e)
        {
            try
            {
                Carts carts = new Carts((Client)((Button)e.OriginalSource).DataContext);
                carts.Show();
            }
            catch(Exception ex)
            {
                MessageBox.Show("Сначало введите данные для клиента");
            }
            
        }

        /// <summary>
        /// Обработка нажатия на меню удаления клиента
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void DellClientMenu_Click(object sender, RoutedEventArgs e)
        {
            if (AccountListGrid?.SelectedItem is Client)
            {
                if (this.DataContext is IndividualViewModel)
                {
                    (this.DataContext as IndividualViewModel).delClient(AccountListGrid.SelectedItem as Individual);
                } 
                else if(this.DataContext is BusinessViewModel)
                    (this.DataContext as BusinessViewModel).delClient(AccountListGrid.SelectedItem as Business);
                else
                    (this.DataContext as VipViewModel).delClient(AccountListGrid.SelectedItem as VipClient);
            }
        }


       
        // }
        /// <summary>
        /// Обработка кнопки добавление клиента
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void AddClientButton_Click(object sender, RoutedEventArgs e)
        {

                
       
            BottonGridLane.Height = new GridLength(0);
        }
        


    }
}
